#!/usr/bin/env python3

import argparse
from pathlib import Path

def bytes_to_decimal(bytes):
    return int(bytes.hex(), 16)

def main():
    parser = argparse.ArgumentParser()
    parser.add_argument('mod_file', type=Path)
    args = parser.parse_args()
    with open(args.mod_file, 'rb') as file:
        mod_file = {"title": file.read(20).decode('utf-8'), "samples": []}
        for x in range(31):
            sample = {}
            sample["name"] = file.read(22).decode('utf-8')
            sample["length"] = bytes_to_decimal(file.read(2))
            sample["finetune"] = bytes_to_decimal(file.read(1))
            sample["volume"] = bytes_to_decimal(file.read(1))
            sample["loop_offset"] = bytes_to_decimal(file.read(2))
            sample["loop_length"] = bytes_to_decimal(file.read(2))
            mod_file["samples"].append(sample)
        print(mod_file["title"])
        for sample in mod_file["samples"]:
            print(sample["name"] + " " + str(sample["length"]))
        print(bytes_to_decimal(file.read(1)))

if __name__ == '__main__':
    main()
